id: P010644
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19922
  title: སྡེབ་བྲིས་ཀྱི་ཕ་ས་དཀར་མཛེས་ཁུལ་གྱི་བྲིས་གཟུགས་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    9a45898afda949f1ae4e98491a14f5c2:
      image_group_id: I2PD20427
      title: ''
      volume_number: 1
      total_pages: 96
